/**
 * Manager-facing WorkBuddy scan/status.
 *
 * Discovery plus delivery status: RabiRoute reads the published session
 * descriptors and the desktop task database, and reports whether a local
 * gateway credential is configured. This module never carries prompt text —
 * the single real message path lives in `src/workbuddySessionBridge.ts`.
 *
 * See docs/workbuddy-agent-adapter-plan.md.
 */

import { agentAdapterManifest } from "../shared/agentAdapterCapabilities.js";
import { workbuddyCredentialStatus } from "../workbuddyHttpAuth.js";
import {
  listWorkbuddySessionDescriptors,
  listWorkbuddyTasks,
  listWorkbuddyWorkspaces,
  normalizeWorkbuddyWorkspace,
  readWorkbuddyTaskRows,
  workbuddyProjectId,
  workbuddySessionsDir
} from "../workbuddySessionStore.js";
import type {
  AgentManagerApiContext,
  AgentScanOptions,
  AgentScanProject,
  AgentScanResult,
  AgentScanSession
} from "./managerApi.js";

export async function scanWorkbuddyAgentAdapter(
  ctx: AgentManagerApiContext,
  options: Pick<
    AgentScanOptions,
    "workbuddyLimit" | "workbuddyOffset" | "workbuddyQuery" | "workbuddyWorkspace"
  > = {}
): Promise<{ agents: { workbuddy: AgentScanResult }; cwdOptions: string[] }> {
  const manifest = agentAdapterManifest("workbuddy");
  const limit = Math.max(1, Math.min(500, Math.floor(options.workbuddyLimit ?? 200)));
  const offset = Math.max(0, Math.floor(options.workbuddyOffset ?? 0));
  const query = String(options.workbuddyQuery || "").trim() || undefined;
  const workspace = String(options.workbuddyWorkspace || "").trim() || undefined;
  const sessionsDir = ctx.workbuddySessionsDir ?? workbuddySessionsDir();
  const databasePath = ctx.workbuddyDatabasePath;

  let descriptors: ReturnType<typeof listWorkbuddySessionDescriptors> = [];
  let rows: ReturnType<typeof readWorkbuddyTaskRows> = [];
  const warnings: string[] = [];
  try {
    descriptors = listWorkbuddySessionDescriptors({ sessionsDir });
  } catch (error) {
    warnings.push(`读取 WorkBuddy 会话进程描述失败：${error instanceof Error ? error.message : String(error)}`);
  }
  try {
    rows = readWorkbuddyTaskRows(databasePath);
  } catch (error) {
    warnings.push(`读取 WorkBuddy 任务库失败：${error instanceof Error ? error.message : String(error)}`);
  }
  if (rows.length === 0) {
    warnings.push("未发现 WorkBuddy 任务；请确认 WorkBuddy 桌面已启动并至少有过一次对话。");
  }

  const allTasks = listWorkbuddyTasks({ databasePath, descriptors, includeArchived: false });
  const filtered = allTasks
    .filter(task => !workspace || normalizeWorkbuddyWorkspace(task.workspace) === normalizeWorkbuddyWorkspace(workspace))
    .filter(task => !query
      || task.name.toLocaleLowerCase().includes(query.toLocaleLowerCase())
      || task.autoTitle.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
  const hasMore = filtered.length > limit;
  const page = filtered.slice(offset, offset + limit);
  const sessions: AgentScanSession[] = page.map(task => ({
    id: task.id,
    name: task.name,
    projectPath: task.workspace,
    ...(workbuddyProjectId(task.workspace) ? { projectId: workbuddyProjectId(task.workspace) } : {}),
    ...(task.updatedAt ? { updatedAt: task.updatedAt } : {}),
    userNamed: task.userNamed,
    status: task.status,
    live: Boolean(task.live && !task.live.stale)
  }));

  const checkEndpoint = ctx.checkHttpEndpoint;
  const liveDescriptors = descriptors.filter(descriptor => descriptor.processAlive && descriptor.endpoint);
  const endpoints = await Promise.all(liveDescriptors.map(async (descriptor) => ({
    label: `WorkBuddy 会话进程 ${descriptor.pid}（${descriptor.kind}）`,
    url: descriptor.endpoint as string,
    healthy: descriptor.stale
      ? false
      : checkEndpoint
        ? await checkEndpoint(descriptor.endpoint as string, 1_500).catch(() => false)
        : true
  })));

  const staleCount = descriptors.filter(descriptor => descriptor.stale || !descriptor.processAlive).length;
  if (staleCount > 0) {
    warnings.push(`有 ${staleCount} 个会话进程描述已过期或进程已退出；这些任务当前不可投递。`);
  }
  const liveWithoutEndpoint = descriptors.filter(descriptor => descriptor.processAlive && !descriptor.endpoint).length;
  if (liveWithoutEndpoint > 0) {
    warnings.push(`有 ${liveWithoutEndpoint} 个会话进程未发布本地网关地址，无法作为投递目标。`);
  }

  // The gateway password is generated by the desktop and injected into session
  // processes; RabiRoute cannot read another process's environment, so the
  // operator supplies it through one local ignored file.
  const credential = await workbuddyCredentialStatus();
  if (!credential.configured) {
    warnings.push(
      `未配置 WorkBuddy 本地网关凭据；请在 ${credential.filePath} 写入 {"password":"<网关密码>"}（该文件已被 git 忽略），否则投递会失败关闭。`
    );
  }
  const deliverableCount = descriptors.filter(descriptor => descriptor.deliverable).length;
  if (deliverableCount === 0 && rows.length > 0) {
    warnings.push("当前没有可投递的 WorkBuddy 会话进程；请在 WorkBuddy 中打开目标任务后再投递。");
  }
  warnings.push(
    "WorkBuddy 投递会进入绑定任务的对话区并由该任务 owner 执行；仍为实验性：凭据需手工配置，桌面配对入口尚未提供。"
  );

  const workspaces = listWorkbuddyWorkspaces(databasePath);
  const projects: AgentScanProject[] = workspaces.map(cwd => ({
    label: workbuddyProjectId(cwd) || cwd,
    path: cwd,
    exists: true
  }));

  return {
    agents: {
      workbuddy: {
        type: manifest.type,
        label: manifest.label,
        maturity: manifest.maturity,
        transport: { ...manifest.transport },
        ...(manifest.host ? { host: { ...manifest.host } } : {}),
        installed: rows.length > 0 || descriptors.length > 0,
        auth: {
          required: true,
          // Only ever claim "configured" — never imply a live login check that
          // was not performed.
          ...(credential.configured ? { loggedIn: true } : {}),
          message: credential.configured
            ? "已检测到 WorkBuddy 本地网关凭据；投递时按会话描述文件动态发现网关地址。"
            : "需要 WorkBuddy 本地网关凭据：会话进程互相共用桌面生成的密码，RabiRoute 无法从另一进程读取，请在本地凭据文件中一次性录入。"
        },
        endpoints,
        projects,
        sessions,
        sessionPage: {
          offset,
          limit,
          returned: sessions.length,
          hasMore,
          ...(hasMore ? { nextOffset: offset + sessions.length } : {})
        },
        warnings
      }
    },
    cwdOptions: projects.map(project => project.path)
  };
}
