import test from "node:test";
import assert from "node:assert/strict";
import { RecordingAsrJobs, RecordingAsrSafeFailure, type RecordingAsrStore, type RecordingAsrJob, type RecordingAsrLease, type RecordingAsrRef, type RecordingAsrResult } from "./recordingAsrJobs.js";
import { recordingManifestHash, type RecordingManifest } from "./recordingArchiveContract.js";
import type { AsrSelectionResult } from "./recordingAsrSelection.js";
const clone = <T>(v:T):T => JSON.parse(JSON.stringify(v));
const selection = (model="provider/model"): AsrSelectionResult => ({ok:true,provider:"provider",model,language:"zh",prompt:null,selectionSource:"pc-microphone-config",configFingerprint:"a".repeat(64)});
function ref(id="one", policy:RecordingManifest["processingPolicy"]="transcribe"):RecordingAsrRef {
  const manifest:RecordingManifest={schemaVersion:1,recordId:id,captureId:"capture",eventId:id,deviceId:"phone",source:"phone",startedAt:1000,endedAt:2000,timeBasis:"received",format:{codec:"pcm_s16le",sampleRate:16000,channels:1},segments:[{sequence:1,bytes:32000,sha256:"a".repeat(64),startedAt:1000}],objects:[{sha256:"a".repeat(64),bytes:32000,offset:0}],gaps:[],processingPolicy:policy,totalBytes:32000,sealed:true};
  return {owner:"phone",manifest,processingVersion:"v1",receipt:{schemaVersion:1,workerId:"pc",storageNamespaceId:"12345678-1234-4234-8234-123456789abc",recordId:id,manifestHash:recordingManifestHash(manifest),totalBytes:32000,segmentCount:1,committedAt:3000,durability:"archived",retention:"indefinite"}};
}
class Store implements RecordingAsrStore {
  jobs=new Map<string,RecordingAsrJob>(); results=new Map<string,RecordingAsrResult>(); fences=new Map<string,string>(); n=0;
  async create(j:Omit<RecordingAsrJob,"revision">){const old=this.jobs.get(j.jobKey);if(old){if(JSON.stringify(old.ref)!==JSON.stringify(j.ref))throw Error("conflict");return clone(old);}const v={...clone(j),revision:String(++this.n)};this.jobs.set(j.jobKey,v);return clone(v);}
  async get(k:string){const j=this.jobs.get(k);return j&&clone(j);}
  async update(k:string,r:string,p:Parameters<RecordingAsrStore["update"]>[2]){const j=this.jobs.get(k);if(!j||j.revision!==r||j.state==="completed")return;const v={...j,...clone(p),revision:String(++this.n)};this.jobs.set(k,v);return clone(v);}
  async claim(k:string,r:string,now:number){const j=this.jobs.get(k);if(!j||j.revision!==r||j.state!=="queued")return;const fence=String(++this.n);this.jobs.set(k,{...j,state:"running",attempt:j.attempt+1,updatedAt:now,revision:fence});this.fences.set(k,fence);return {jobKey:k,fence};}
  async finish(l:RecordingAsrLease,state:"failed"|"ambiguous",error:string,now:number){if(this.fences.get(l.jobKey)!==l.fence)return false;this.fences.delete(l.jobKey);const j=this.jobs.get(l.jobKey)!;this.jobs.set(l.jobKey,{...j,state,error,updatedAt:now,revision:String(++this.n)});return true;}
  async commitResult(l:RecordingAsrLease,result:RecordingAsrResult,now:number){if(this.fences.get(l.jobKey)!==l.fence)return false;this.results.set(l.jobKey,clone(result));this.fences.delete(l.jobKey);const j=this.jobs.get(l.jobKey)!;this.jobs.set(l.jobKey,{...j,state:"completed",updatedAt:now,revision:String(++this.n)});return true;}
  async recoverable(){return {jobs:[...this.jobs.values()].map(clone)};}
  async recoverAmbiguous(k:string,r:string,now:number){const j=this.jobs.get(k);if(!j||j.revision!==r||j.state!=="running")return false;return this.finish({jobKey:k,fence:this.fences.get(k)!},"ambiguous","orphan",now);}
}
function setup(compute:Parameters<typeof factory>[1], resolve=async()=>selection()){return factory(new Store(),compute,resolve);}
function factory(store:Store,compute:(...args:Parameters<import("./recordingAsrJobs.js").RecordingAsrDependencies["transcribeLocal"]>)=>Promise<RecordingAsrResult>,resolve=async()=>selection()){const jobs=new RecordingAsrJobs({store,resolveSelection:resolve,transcribeLocal:compute,clock:()=>4000,changed:()=>{}});return {store,jobs};}
const deferred=()=>{let release!:()=>void;const promise=new Promise<void>(r=>release=r);return {promise,release};};
test("single concurrency, duplicate enqueue and empty text commit",async()=>{let calls=0,active=0,max=0;const {store,jobs}=setup(async()=>{calls++;max=Math.max(max,++active);await new Promise(r=>setImmediate(r));active--;return {text:""};});const a=await jobs.enqueue(ref());await Promise.all([jobs.enqueue(ref()),jobs.enqueue(ref("two"))]);await jobs.idle();assert.equal(calls,2);assert.equal(max,1);assert.equal(store.results.get(a!)?.text,"");await jobs.enqueue(ref());await jobs.idle();assert.equal(calls,2);});
test("model blocked leaves receipt unchanged, excludes local-only and agent",async()=>{let calls=0;const input=ref(),original=clone(input.receipt);const {store,jobs}=setup(async()=>{calls++;return {text:"x"};},async()=>({ok:false,code:"blocked_model_configuration",reason:"model_unavailable"}));const key=await jobs.enqueue(input);await jobs.idle();assert.equal(store.jobs.get(key!)?.state,"blocked");assert.deepEqual(input.receipt,original);assert.equal(await jobs.enqueue(ref("local","local_only")),undefined);assert.equal(await jobs.enqueue(ref("agent","agent")),undefined);assert.equal(calls,0);});
test("safe retry preserves frozen selection",async()=>{let calls=0,resolves=0;const models:string[]=[];const {store,jobs}=setup(async(_r,s)=>{models.push(s.model);if(++calls===1)throw new RecordingAsrSafeFailure("no dispatch");return {text:"ok"};},async()=>{resolves++;return selection("provider/first");});const key=(await jobs.enqueue(ref()))!;await jobs.idle();assert.equal(store.jobs.get(key)?.state,"failed");assert.equal(await jobs.retry(key),true);await jobs.idle();assert.deepEqual(models,["provider/first","provider/first"]);assert.equal(resolves,1);});
test("timeout ambiguous never retry or restore; explicit new version recomputes",async()=>{let calls=0;const {store,jobs}=setup(async()=>{calls++;throw Error("timeout");});const key=(await jobs.enqueue(ref()))!;await jobs.idle();assert.equal(store.jobs.get(key)?.state,"ambiguous");assert.equal(await jobs.retry(key),false);await jobs.restore();await jobs.idle();assert.equal(calls,1);await assert.rejects(jobs.recompute(key,"v1"));const next=await jobs.recompute(key,"v2");await jobs.idle();assert.notEqual(next,key);assert.equal(calls,2);});
test("orphan running restored as ambiguous without ASR",async()=>{const s=new Store();let calls=0;const a=factory(s,async()=>{calls++;return {text:"bad"};});const input=ref();const {recordingAsrJobKey}=await import("./recordingAsrJobs.js");const key=recordingAsrJobKey(input);const j=await s.create({jobKey:key,ref:input,state:"queued",attempt:0,updatedAt:0});await s.claim(key,j.revision,1);await a.jobs.restore();await a.jobs.idle();assert.equal(calls,0);assert.equal(s.jobs.get(key)?.state,"ambiguous");});
test("shutdown abort and late response cannot publish",async()=>{const entered=deferred(),end=deferred();const {store,jobs}=setup(async(_r,_s,_k,signal)=>{entered.release();await end.promise;assert.equal(signal.aborted,true);return {text:"late"};});const key=(await jobs.enqueue(ref()))!;await entered.promise;await jobs.shutdown();end.release();await jobs.idle();assert.equal(store.results.size,0);assert.equal(store.jobs.get(key)?.state,"ambiguous");});
test("foreign fence rejects result; conflicting immutable ref rejected",async()=>{const entered=deferred(),end=deferred();const {store,jobs}=setup(async()=>{entered.release();await end.promise;return {text:"late"};});const input=ref(),key=(await jobs.enqueue(input))!;await entered.promise;store.fences.set(key,"new-generation");end.release();await jobs.idle();assert.equal(store.results.size,0);const conflict=clone(input);conflict.receipt.workerId="other";await assert.rejects(jobs.enqueue(conflict),/conflict/);});
