services:
  open-xiaoai-rabiroute:
    image: idootop/open-xiaoai-migpt:latest
    container_name: open-xiaoai-rabiroute
    ports:
      - "4399:4399"
    environment:
      RABIROUTE_XIAOAI_BRIDGE_URL: "http://host.docker.internal:8798"
      XIAOAI_DEVICE_ID: "xiaoai_lx06"
      XIAOAI_DEVICE_NAME: "小爱音箱 Pro"
      XIAOAI_AREA: "home"
    volumes:
      - ./open-xiaoai-migpt-rabiroute.config.ts:/app/config.ts
    stdin_open: true
    tty: true
