import test from 'node:test';import assert from 'node:assert/strict';
import {createProfileMcpEditor} from './rabilink-profile-mcp-editor.mjs';import {createProfileReceiptPolicy} from './rabilink-agent-profile-ui-receipt.mjs';
class Node{constructor(){this.children=[];this.events={};this.style={};}appendChild(n){this.children.push(n);}replaceChildren(){this.children=[];}setAttribute(){}addEventListener(k,f){this.events[k]=f;}click(){if(!this.disabled)this.events.click?.();}}
function setup(items=[]){const e=createProfileMcpEditor({document:{createElement:()=>new Node()},container:new Node(),validate:mcp=>createProfileReceiptPolicy().profile({revision:1,id:'x',name:'X',systemPrompt:'',skills:[],mcp}).mcp});e.set(items);e.lock(false);return e;}
const other=i=>({id:'unknown-'+i,label:'<img onerror=alert(1)>',enabled:true});
test('absent remains absent; actual toggle and label input create only explicit reference',()=>{const e=setup();assert.deepEqual(e.get(),[]);e.nodes.enabled.checked=true;e.nodes.enabled.events.change();e.nodes.label.value='My tools';e.nodes.label.events.input();assert.deepEqual(e.get(),[{id:'rabi-knowledge',label:'My tools',enabled:true}]);e.nodes.enabled.checked=false;e.nodes.enabled.events.change();assert.equal(e.get()[0].label,'My tools');assert.equal(e.get()[0].enabled,false);const copy=e.get();copy[0].label='wrong';assert.equal(e.get()[0].label,'My tools');});
test('unknown enabled items preserved and safely displayed, failed set does not clear draft',()=>{const input=[other(1)];const e=setup(input);assert.deepEqual(e.get(),input);assert.match(e.nodes.unknown.children[0].textContent,/<img/);assert.throws(()=>e.set([{id:'bad'}]));assert.deepEqual(e.get(),input);e.nodes.toggle.click();e.nodes.toggle.click();assert.deepEqual(e.get(),input);});
test('sixteen unknown items disable addition, existing known can still enable',()=>{const list=Array.from({length:16},(_,i)=>other(i));const e=setup(list);assert.equal(e.nodes.enabled.disabled,true);list[3]={id:'rabi-knowledge',label:'Old',enabled:false};e.set(list);assert.equal(e.nodes.enabled.disabled,false);e.nodes.enabled.checked=true;e.nodes.enabled.events.change();assert.equal(e.get().length,16);assert.equal(e.get()[3].enabled,true);});
test('invalid raw retained; empty label, extra credential, duplicates rejected',()=>{const e=setup([{id:'rabi-knowledge',label:'Valid',enabled:false}]);e.nodes.label.value='';e.nodes.label.events.input();assert.throws(()=>e.get());e.nodes.toggle.click();e.nodes.raw.value='[';e.nodes.toggle.click();assert.equal(e.nodes.raw.hidden,false);assert.equal(e.nodes.raw.value,'[');assert.throws(()=>e.get());for(const value of [[{...other(1),token:'no'}],[other(1),other(1)]]){e.nodes.raw.value=JSON.stringify(value);assert.throws(()=>e.get());}e.nodes.raw.value='[]';e.nodes.toggle.click();assert.deepEqual(e.get(),[]);});
test('freeze disables all mutation and advanced controls',()=>{const e=setup();e.lock(true);assert.equal(e.nodes.enabled.disabled,true);assert.equal(e.nodes.label.disabled,true);assert.equal(e.nodes.toggle.disabled,true);assert.equal(e.nodes.raw.disabled,true);e.nodes.enabled.checked=true;e.nodes.enabled.events.change();assert.deepEqual(e.get(),[]);});
